#!/bin/bash
source /etc/profile.env
TUPLE=##CHOST##
DISTCC=$(type -p distcc)
DISTCC=${DISTCC:-/usr/bin/distcc}

progname="${0##*/}"
case "${progname}" in
	c99)
	if type -p "${TUPLE}-gcc" &>/dev/null; then
		exec "${DISTCC}" "${TUPLE}-gcc" -std=c99 "$@"
	else
		exec "${DISTCC}" "${progname}" "$@"
	fi
	;;
	cc|gcc|c++|g++)
	if type -p "${TUPLE}-g${progname:(-2)}" &>/dev/null; then
		exec "${DISTCC}" "${TUPLE}-g${progname:(-2)}" "$@"
	else
		exec "${DISTCC}" "${progname}" "$@"
	fi
	;;
	gcc-*|g++-*)
	if type -p "${TUPLE}-${progname}" &>/dev/null; then
		exec "${DISTCC}" "${TUPLE}-${progname}" "$@"
	else
		exec "${DISTCC}" "${progname}" "$@"
	fi
	;;
	clang*)
	if args_not_target "$@"; then
		exec  "${DISTCC}" "${progname}" --target="${TUPLE}" "$@"
	else
		exec  "${DISTCC}" "${progname}" "$@"
	fi
	;;
	*-*-*-*-clang*)
	if type -p "clang${progname##*-clang}" &>/dev/null && \
	   args_not_target "$@"; then
		TUPLE=${progname%%-clang*}
		progname=clang${progname##*-clang}
		exec  "${DISTCC}" "${progname}" --target="${TUPLE}" "$@"
	else
		exec  "${DISTCC}" "${progname}" "$@"
	fi
	;;
	*)
	exec "${DISTCC}" "${progname}" "$@"
	;;
esac

args_not_target() {
	(($# > 0)) || return 0
	local arg
	for arg in "$@"; do
		[[ "$arg" != "--target="*  && "$arg" != "-target "* && "$arg" != "-triple "* ]] || return 1
	done
}
